// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddComment(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddComment'](arg1, arg2, arg3);
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateIssue(arg1, arg2) {
  return window['go']['main']['App']['CreateIssue'](arg1, arg2);
}

export function CreateProjectRoot(arg1) {
  return window['go']['main']['App']['CreateProjectRoot'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DetectMode() {
  return window['go']['main']['App']['DetectMode']();
}

export function GetAppBootstrap() {
  return window['go']['main']['App']['GetAppBootstrap']();
}

export function GetIssue(arg1, arg2) {
  return window['go']['main']['App']['GetIssue'](arg1, arg2);
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListIssues(arg1, arg2) {
  return window['go']['main']['App']['ListIssues'](arg1, arg2);
}

export function RenameCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameCategory'](arg1, arg2);
}

export function SaveLastProjectRoot(arg1) {
  return window['go']['main']['App']['SaveLastProjectRoot'](arg1);
}

export function UpdateIssue(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateIssue'](arg1, arg2, arg3);
}

export function ValidateProjectRoot(arg1) {
  return window['go']['main']['App']['ValidateProjectRoot'](arg1);
}

export function VerifyContractorPassword(arg1) {
  return window['go']['main']['App']['VerifyContractorPassword'](arg1);
}
