// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {present} from '../models';

export function AddComment(arg1:string,arg2:string,arg3:present.CommentCreateDTO):Promise<present.Response>;

export function CreateCategory(arg1:string):Promise<present.Response>;

export function CreateIssue(arg1:string,arg2:present.IssueCreateDTO):Promise<present.Response>;

export function CreateProjectRoot(arg1:string):Promise<present.Response>;

export function DeleteCategory(arg1:string):Promise<present.Response>;

export function DetectMode():Promise<present.Response>;

export function GetAppBootstrap():Promise<present.Response>;

export function GetIssue(arg1:string,arg2:string):Promise<present.Response>;

export function ListCategories():Promise<present.Response>;

export function ListIssues(arg1:string,arg2:present.IssueListQueryDTO):Promise<present.Response>;

export function RenameCategory(arg1:string,arg2:string):Promise<present.Response>;

export function SaveLastProjectRoot(arg1:string):Promise<present.Response>;

export function UpdateIssue(arg1:string,arg2:string,arg3:present.IssueUpdateDTO):Promise<present.Response>;

export function ValidateProjectRoot(arg1:string):Promise<present.Response>;

export function VerifyContractorPassword(arg1:string):Promise<present.Response>;
